[package]
name = "pik"
version = "0.5.0"
edition = "2021"
authors = ["Jacek Kurlit"]
keywords = ["terminal", "process", "linux", "system", "kill"]
categories = ["command-line-utilities"]
license-file = "LICENSE"
description = "pik - process interactive kill"
repository = "https://github.com/jacek-kurlit/pik"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.28"
ratatui = "0.28"
anyhow = "1.0.79"
sysinfo = "0.31"
listeners = "0.2.1"
chrono = "0.4"
clap = { version = "4.5", features = ["derive"] }
